# 简介 & 备注
# DeepPointMap发行版基础变体

# 基本参数，注：gpu_index use_ddp checkpoint 的非默认参数请在命令行直接传入
name: DeepPointMap
version: v1.0
mode: infer
num_workers: 2
multi_agent: false
use_cuda: true

# 数据参数
infer_src:
  [
    # [E:\Dataset\Original_MuRan\ParkingLot\Ouster, /root/dataset/original_MulRan/ParkingLot/Ouster],

    # [/root/dataset/original_MulRan/DCC01/Ouster],
    # [/root/dataset/original_MulRan/DCC02/Ouster],
    # [/root/dataset/original_MulRan/DCC03/Ouster],

    # [/root/dataset/original_MulRan/KAIST01/Ouster],
    # [/root/dataset/original_MulRan/KAIST02/Ouster],
    # [/root/dataset/original_MulRan/KAIST03/Ouster],

    # [/root/dataset/original_MulRan/Riverside01/Ouster],
    # [/root/dataset/original_MulRan/Riverside02/Ouster],
    # [/root/dataset/original_MulRan/Riverside03/Ouster],

    # [/root/dataset/original_MulRan/Sejong01/Ouster],
    # [/root/dataset/original_MulRan/Sejong02/Ouster],
    # [/root/dataset/original_MulRan/Sejong03/Ouster],

    # [/root/dataset/Original_MuRan/Sejong02/Ouster],
    # [/root/dataset/Original_MuRan/Sejong03/Ouster],

    # [E:/Dataset/DeepPointMap_Datasets/SemanticKITTI_mini/00/velodyne,H:/Dataset/DeepPointMap_Datasets/SemanticKITTI_mini/00/velodyne,/root/dataset/DeepPointMap_Datasets/SemanticKITTI/00/velodyne],
    # [E:/Dataset/DeepPointMap_Datasets/SemanticKITTI_mini/01/velodyne,H:/Dataset/DeepPointMap_Datasets/SemanticKITTI_mini/01/velodyne,/root/dataset/DeepPointMap_Datasets/SemanticKITTI/01/velodyne],
    # [E:/Dataset/DeepPointMap_Datasets/SemanticKITTI_mini/02/velodyne,H:/Dataset/DeepPointMap_Datasets/SemanticKITTI_mini/02/velodyne,/root/dataset/DeepPointMap_Datasets/SemanticKITTI/02/velodyne],
    # [E:/Dataset/DeepPointMap_Datasets/SemanticKITTI_mini/03/velodyne,H:/Dataset/DeepPointMap_Datasets/SemanticKITTI_mini/03/velodyne,/root/dataset/DeepPointMap_Datasets/SemanticKITTI/03/velodyne],
    # [E:/Dataset/DeepPointMap_Datasets/SemanticKITTI_mini/04/velodyne,H:/Dataset/DeepPointMap_Datasets/SemanticKITTI_mini/04/velodyne,/root/dataset/DeepPointMap_Datasets/SemanticKITTI/04/velodyne],
    # [E:/Dataset/DeepPointMap_Datasets/SemanticKITTI_mini/05/velodyne,H:/Dataset/DeepPointMap_Datasets/SemanticKITTI_mini/05/velodyne,/root/dataset/DeepPointMap_Datasets/SemanticKITTI/05/velodyne],
    # [E:/Dataset/DeepPointMap_Datasets/SemanticKITTI_mini/06/velodyne,H:/Dataset/DeepPointMap_Datasets/SemanticKITTI_mini/06/velodyne,/root/dataset/DeepPointMap_Datasets/SemanticKITTI/06/velodyne],
    # [E:/Dataset/DeepPointMap_Datasets/SemanticKITTI_mini/07/velodyne,H:/Dataset/DeepPointMap_Datasets/SemanticKITTI_mini/07/velodyne,/root/dataset/DeepPointMap_Datasets/SemanticKITTI/07/velodyne],
    [E:/Dataset/DeepPointMap_Datasets/SemanticKITTI_mini/08/velodyne,H:/Dataset/DeepPointMap_Datasets/SemanticKITTI_mini/08/velodyne,/root/dataset/DeepPointMap_Datasets/SemanticKITTI/08/velodyne],
    
    
    [/root/dataset/original_KITTI_360/2013_05_28_drive_0009_sync/velodyne_points/data],
  ]
infer_tgt: ./log_infer/evaluation_all

transforms:
  VoxelSample: { voxel_size: 0.3, retention: center }
  ToGPU: {}
  DistanceSample: { min_dis: 1.0, max_dis: 60.0 }
  OutlierFilter: { nb_neighbors: 10, std_ratio: 3.0 }
  CoordinatesNormalization: { ratio: 60.0 }
  ToCPU: {}
  ToTensor: { padding_to: -1 }

# 模型参数
encoder:
  npoint: [4096, 1024, 256, 64, 16]
  radius_list: [[0.05, 0.1], [0.1, 0.2], [0.2, 0.4, 0.4], [0.4, 0.8], [0.8, 1.6]]
  nsample_list: [[32, 32], [32, 32], [32, 32, 32], [32, 32], [16, 16]]
  in_channel: 3
  out_channel: 128
  width: 16
  expansion: 4
  upsample_layers: 2
  sample:
    [
      { type: "fps-t3d" },
      { type: "fps-t3d" },
      { type: "fps-t3d" },
      { type: "fps-t3d" },
      { type: "fps-t3d" },
    ]
  norm: LN
  bias: True

decoder:
  in_channel: 128
  model_channel: 256
  attention_layers: 3

## loss
loss:
  tau: 0.1
  eps_offset: 2.0

# SlamSystem
slam_system:
  # Overall
  coor_scale: 60

  # Odometer
  odometer_candidates_num: 1
  registration_sample_odometer: 0.5

  # Mapping
  edge_confidence_drop: 0.60
  edge_rmse_drop: 0.50
  max_continuous_drop_scan: 5
  continuous_drop_scan_strategy: recover
  key_frame_distance: auto

  enable_s2m_adjust: true # original: backend_loop_m2m_adjust
  registration_sample_mapping: 0.5

  # Loop
  enable_loop_closure: true # original: backend_loop_closure
  loop_detection_gap: 0 # original: backend_loop_time_gap_min
  loop_detection_transaction_gap: 10.0
  loop_detection_trust_range: 3 # original: LOOP_NEAREST_GRAPH_DIST
  loop_detection_gnss_distance: -1 # original: LOOP_MAX_GPS_DIST_THRESHOLD_MAX
  loop_detection_pred_distance: 100.0 # original: backend_loop_pred_dist_max
  loop_detection_rotation_min: 30.0 # original: backend_loop_pred_rot_min
  loop_detection_translation_min: 10.0
  loop_detection_prob_acpt_threshold: 0.7 # original: backend_loop_threshold
  loop_detection_candidates_num: 1 # original: backend_loop_edge_per_scan
  registration_sample_loop: 0.5

  loop_detection_confidence_acpt_threshold: 0.6 # original: LOOP_VERIFY_CONFIDENCE
  enable_global_optimization: true
  global_optimization_gap: 0
  # end
