name: DeepPointMap
version: v1.1
num_workers: 8
use_cuda: true

dataset:
- name: KITTI
  root: /root/dataset/KITTI_v4.0_SUMA_NoVisual
  scenes:
  - '00'
  - '01'
  - '02'
  - '03'
  - '04'
  - '05'
  reader:
    type: npz
- name: KITTI_360
  root: /root/dataset/KITTI360_v4.0_NoVisual
  scenes:
  - 2013_05_28_drive_0000_sync
  - 2013_05_28_drive_0002_sync
  - 2013_05_28_drive_0003_sync
  - 2013_05_28_drive_0004_sync
  - 2013_05_28_drive_0005_sync
  - 2013_05_28_drive_0006_sync
  reader:
    type: npz
- name: KITTI_CARLA
  root: /root/dataset/KITTICarla_v4.0_NoVisual
  scenes:
  - Town01
  - Town02
  - Town03
  - Town04
  - Town05
  - Town06
  - Town07
  reader:
    type: npz
- name: MulRan
  root: /root/dataset/MulRan_v4.0_NoVisual
  scenes:
  - DCC01
  - DCC02
  - DCC03
  - Sejong01
  - Sejong02
  - Sejong03
  reader:
    type: npz
train:
  auto_cast: false
  log_cycle: 320
  save_cycle: 1
  registration:
    num_epochs: 7
    batch_size: 1
    distance: 20
    fill: true
    K_max: 32
    map_size_max: 16
    K_0: 2
    K_mult: 2
    mult_epoch:
    - 2
    - 3
    - 4
    - 6
    optimizer:
      type: AdamW
      kwargs:
        lr: 0.001
        weight_decay: 0.0001
    scheduler:
      type: cosine
      kwargs:
        T_max: 6
        eta_min: 1.0e-05
  loop_detection:
    num_epochs: 10
    batch_size: 32
    distance: 20
    optimizer:
      type: AdamW
      kwargs:
        lr: 0.001
        weight_decay: 0.0001
    scheduler:
      type: cosine
      kwargs:
        T_max: 9
        eta_min: 1.0e-05
loss:
  tau: 0.1
  offset_value: mahalanobis
  eps_positive: 1.0
  eps_offset: 2.0
  lambda_p: 1.0
  lambda_c: 0.1
  lambda_o: 1.0
transforms:
  RandomShuffle:
    p: 1.0
  VoxelSample:
    voxel_size: 0.3
    retention: first
  DistanceSample:
    min_dis: 1.0
    max_dis: 60.0
  RandomDrop:
    max_ratio: 0.5
    p: 1.0
  RandomShield:
    angle_range:
    - 10
    - 150
    dis_range:
    - 2
    - 10
    max_num: 3
    p: 0.1
  RandomSample:
    num: 16384
  RandomRT:
    r_mean: 0
    r_std: 3.1416
    t_mean: 0
    t_std: 3
    p: 1.0
    pair: false
  RandomPosJitter:
    mean: 0
    std: 0.005
    p: 1.0
  CoordinatesNormalization:
    ratio: 60.0
  ToTensor:
    padding_to: 16384
    use_calib: true
encoder:
  npoint:
  - 4096
  - 1024
  - 256
  - 64
  - 16
  radius_list:
  - - 0.05
    - 0.1
  - - 0.1
    - 0.2
  - - 0.2
    - 0.4
    - 0.4
  - - 0.4
    - 0.8
  - - 0.8
    - 1.6
  nsample_list:
  - - 32
    - 32
  - - 32
    - 32
  - - 32
    - 32
    - 32
  - - 32
    - 32
  - - 16
    - 16
  in_channel: 3
  out_channel: 128
  width: 16
  expansion: 4
  upsample_layers: 2
  sample:
  - type: fps-t3d
  - type: fps-t3d
  - type: fps-t3d
  - type: fps-t3d
  - type: fps-t3d
  norm: LN
  bias: true
decoder:
  in_channel: 128
  model_channel: 256
  attention_layers: 3
slam_system:
  coor_scale: 60
  odometer_candidates_num: 1
  registration_sample_odometer: 0.5
  edge_confidence_drop: 0.6
  edge_rmse_drop: 0.5
  max_continuous_drop_scan: 5
  continuous_drop_scan_strategy: recover
  key_frame_distance: auto
  enable_s2m_adjust: true
  registration_sample_mapping: 0.5
  enable_loop_closure: true
  loop_detection_gap: 0
  loop_detection_transaction_gap: 10.0
  loop_detection_trust_range: 3
  loop_detection_gnss_distance: -1
  loop_detection_pred_distance: 100.0
  loop_detection_rotation_min: 30.0
  loop_detection_translation_min: 10.0
  loop_detection_prob_acpt_threshold: 0.7
  loop_detection_candidates_num: 1
  registration_sample_loop: 0.5
  loop_detection_confidence_acpt_threshold: 0.6
  enable_global_optimization: true
  global_optimization_gap: 0
